"""empty message

Revision ID: 678f17894668
Revises: 
Create Date: 2022-11-10 16:55:33.858809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678f17894668'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anbima_vna')
    op.drop_table('ima_anbima')
    op.drop_table('crica_anbima')
    op.drop_table('components_ima_anbima')
    op.drop_table('debentures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debentures',
    sa.Column('codigo_ativo', sa.VARCHAR(length=30, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_referencia', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('pu', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('grupo', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taxa_indicativa', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('percentual_taxa', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_vencimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_finalizado', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('taxa_compra', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('taxa_venda', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('desvio_padrao', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('val_min_intervalo', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('val_max_intervalo', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('percent_pu_par', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('percent_reune', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('emissor', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('referencia_ntnb', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo_ativo', 'data_referencia', name='PK__debentur__1AABFDA0A85031FE')
    )
    op.create_table('components_ima_anbima',
    sa.Column('indice', sa.VARCHAR(length=30, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_referencia', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tipo_titulo', sa.VARCHAR(length=30, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_vencimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('codigo_selic', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_isin', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('taxa_indicativa', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('pu', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('pu_juros', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantidade_componentes', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantidade_teorica', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('valor_mercado', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('peso_componente', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('prazo_vencimento', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('duration', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('pmr', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('convexidade', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['indice', 'data_referencia'], ['ima_anbima.indice', 'ima_anbima.data_referencia'], name='FK__components_ima_a__3DE82FB7'),
    sa.PrimaryKeyConstraint('indice', 'data_referencia', 'tipo_titulo', 'data_vencimento', name='PK__componen__BC608E1E01C41A6E')
    )
    op.create_table('crica_anbima',
    sa.Column('codigo_ativo', sa.VARCHAR(length=30, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_referencia', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('emissor', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('originador', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('originador_credito', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('serie', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emissao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_vencimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('taxa_compra', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('taxa_venda', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('taxa_indicativa', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('desvio_padrao', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('vl_pu', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('pu', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('percent_pu_par', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('tipo_remuneracao', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('taxa_correcao', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_finalizado', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('percent_reune', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('data_referencia_ntnb', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('referencia_ntnb', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tipo_contrato', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo_ativo', 'data_referencia', name='PK__crica_an__1AABFDA0DA26AFEA')
    )
    op.create_table('ima_anbima',
    sa.Column('indice', sa.VARCHAR(length=30, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_referencia', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('variacao_ult12m', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('variacao_ult24m', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('numero_indice', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('variacao_diaria', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('variacao_anual', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('variacao_mensal', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('peso_indice', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantidade_titulos', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('valor_mercado', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('pmr', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('convexidade', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('yield', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('redemption_yield', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('indice', 'data_referencia', name='PK__ima_anbi__804CE22ACBAB944E')
    )
    op.create_table('anbima_vna',
    sa.Column('data_referencia', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tipo_titulo', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('codigo_selic', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('index', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('tipo_correcao', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_validade', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('vna', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('data_referencia', 'codigo_selic', name='PK__anbima_v__378E7E816391C5E3')
    )
    # ### end Alembic commands ###
